url: https://y7kim.github.io
baseurl: /sajacafe

# Site settings
title: Saja Cafe
email: lee.theodore@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Teddy Lee
  pic: teddy
  position: Baby Saja
  social:
    - title: instagram
      url: https://www.instagram.com/teddyosaurusrex/
    - title: facebook
      url: https://www.facebook.com/teddyosaurusrex/
    - title: linkedin
      url: https://www.linkedin.com/in/lee-theodore/

- name: James Lo
  pic: james
  position: Mystery Saja
  social:
    - title: instagram
      url: https://www.instagram.com/lo__jam/
    - title: facebook
      url: https://www.facebook.com/james.lo.5268
    - title: linkedin
      url: https://www.linkedin.com/in/james-lo-m-s-99058120a/

- name: Daniel Yoon
  pic: daniel
  position: Abby Saja
  social:
    - title: instagram
      url: https://www.instagram.com/danielyooon/
    - title: facebook
      url: https://www.facebook.com/daniel.yoon.587
    - title: linkedin
      url: https://www.linkedin.com/in/daniel-yoon-04b779b9/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty